name: proteinmpnn
channels:
  - pytorch
  - dglteam
  - pyg
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - biopython
  - jupyterlab
  - pandas
  - numpy=1.21.5
  - scipy=1.7.3
  - matplotlib
  - seaborn
  - pytorch=1.11
  - dgl-cuda11.3
  - pyg
  - requests=2.28.1
  - openmm=7.5.1
  


